import {
  diiwan,
  giveagift,
  easyjob,
  zixes,
  ricky,
  notes,
  games,
  anime,
  security,
  queuingTheory,
  VG,
  restaurant,
  ministries,
  besorus,
  aqua,
  t3lm,
  contacts,
  car,
  KFC,
  we,
  saudi,
  portfolio
} from "../shared/images";

export const projects = [
  {
    _id: "proj_1",
    type: ["freelance", "fullstack"],
    name: "Diwan Amlak",
    imgUrl: diiwan,
    videoUrl: "#",
    github: "https://github.com/BassamHafez/Diwan",
    live: "https://diiwan.com",
    tools: [
      "React Js",
      "Redux Toolkit",
      "React Bootstrap",
      "Css",
      "Html",
      "Node Js",
      "Mongo db",
    ],
    desc: "A modern platform designed to enhance the financial efficiency of real estate portfolios for owners and managers.",
    features: [
      "Enables users to manage estates, compounds, contracts, revenues, expenses and more.",
      "Financial management of portfolios, tenant management, rent collection, and maintenance tracking.",
      "Performance indicators for portfolios, such as occupancy rates and financial comparisons.",
      "Notifications, including SMS & Mail alerts, to streamline tenant communication and improve rental efficiency.",
      "Centralized property management, with detailed tracking of tenant payments and property documents.",
      "Storage and classification of documents related to owners and tenants by property.",
      "Dynamic Packages for pricing plans with Electronic payment gateway",
      "Add more that admin to the same account, controlling their permissions",
      "Strong Dashboard for owners and landlords (or brokers)",
    ],
  },
  {
    _id: "proj_2",
    type: ["freelance", "fullstack"],
    name: "Give A Gift",
    imgUrl: giveagift,
    videoUrl: "#",
    live: "https://www.giveagift.com.sa/",
    tools: [
      "React Js",
      "Konva.Js",
      "Redux Toolkit",
      "React Bootstrap",
      "Css",
      "Html",
      "Node Js",
      "Mongo db",
    ],
    desc: "A modern platform designed to enhance the financial efficiency of real estate portfolios for owners and managers.",
    features: [
      "Enables users to manage estates, compounds, contracts, revenues, expenses and more.",
      "Financial management of portfolios, tenant management, rent collection, and maintenance tracking.",
      "Performance indicators for portfolios, such as occupancy rates and financial comparisons.",
      "Notifications, including SMS & Mail alerts, to streamline tenant communication and improve rental efficiency.",
      "Centralized property management, with detailed tracking of tenant payments and property documents.",
      "Storage and classification of documents related to owners and tenants by property.",
      "Dynamic Packages for pricing plans with Electronic payment gateway",
      "Add more that admin to the same account, controlling their permissions",
      "Strong Dashboard for owners and landlords (or brokers)",
    ],
  },
  {
    _id: "proj_3",
    type: ["fullstack"],
    name: "Easy Job",
    imgUrl: easyjob,
    videoUrl: "#",
    live: "#",
    tools: [
      "React Js",
      "Redux Toolkit",
      "Leaflet",
      "React Bootstrap",
      "Css",
      "Html",
      "Node Js",
      "mySQL",
    ],
    desc: "A modern platform designed to enhance the financial efficiency of real estate portfolios for owners and managers.",
    features: [
      "Enables users to manage estates, compounds, contracts, revenues, expenses and more.",
      "Financial management of portfolios, tenant management, rent collection, and maintenance tracking.",
      "Performance indicators for portfolios, such as occupancy rates and financial comparisons.",
      "Notifications, including SMS & Mail alerts, to streamline tenant communication and improve rental efficiency.",
      "Centralized property management, with detailed tracking of tenant payments and property documents.",
      "Storage and classification of documents related to owners and tenants by property.",
      "Dynamic Packages for pricing plans with Electronic payment gateway",
      "Add more that admin to the same account, controlling their permissions",
      "Strong Dashboard for owners and landlords (or brokers)",
    ],
  },
  {
    _id: "proj_4",
    type: ["react"],
    name: "Zixes Movies",
    imgUrl: zixes,
    videoUrl: "#",
    live: "https://bassamhafez.github.io/Zixes-Movies/#/home",
    tools: [
      "React Js",
      "Bootstrap",
      "Css",
      "Html",
      "External Api (Movies)",
      "Route Api (Auth)",
    ],
    desc: "A modern platform designed to enhance the financial efficiency of real estate portfolios for owners and managers.",
    features: [
      "Enables users to manage estates, compounds, contracts, revenues, expenses and more.",
      "Financial management of portfolios, tenant management, rent collection, and maintenance tracking.",
      "Performance indicators for portfolios, such as occupancy rates and financial comparisons.",
      "Notifications, including SMS & Mail alerts, to streamline tenant communication and improve rental efficiency.",
      "Centralized property management, with detailed tracking of tenant payments and property documents.",
      "Storage and classification of documents related to owners and tenants by property.",
      "Dynamic Packages for pricing plans with Electronic payment gateway",
      "Add more that admin to the same account, controlling their permissions",
      "Strong Dashboard for owners and landlords (or brokers)",
    ],
  },
  {
    _id: "proj_5",
    type: ["react"],
    name: "Ricky Pet Shop",
    imgUrl: ricky,
    videoUrl: "#",
    live: "#",
    tools: [
      "React Js",
      "React Bootstrap",
      "Css",
      "Html",
      "External Api (Pets)",
      "Route Api (Auth)",
    ],
    desc: "A modern platform designed to enhance the financial efficiency of real estate portfolios for owners and managers.",
    features: [
      "Enables users to manage estates, compounds, contracts, revenues, expenses and more.",
      "Financial management of portfolios, tenant management, rent collection, and maintenance tracking.",
      "Performance indicators for portfolios, such as occupancy rates and financial comparisons.",
      "Notifications, including SMS & Mail alerts, to streamline tenant communication and improve rental efficiency.",
      "Centralized property management, with detailed tracking of tenant payments and property documents.",
      "Storage and classification of documents related to owners and tenants by property.",
      "Dynamic Packages for pricing plans with Electronic payment gateway",
      "Add more that admin to the same account, controlling their permissions",
      "Strong Dashboard for owners and landlords (or brokers)",
    ],
  },
  {
    _id: "proj_6",
    type: ["fullstack"],
    name: "Notes App",
    imgUrl: notes,
    videoUrl: "#",
    live: "#",
    tools: ["React Js", "React Bootstrap", "Css", "Html", "Node Js", "mySQL"],
    desc: "A modern platform designed to enhance the financial efficiency of real estate portfolios for owners and managers.",
    features: [
      "Enables users to manage estates, compounds, contracts, revenues, expenses and more.",
      "Financial management of portfolios, tenant management, rent collection, and maintenance tracking.",
      "Performance indicators for portfolios, such as occupancy rates and financial comparisons.",
      "Notifications, including SMS & Mail alerts, to streamline tenant communication and improve rental efficiency.",
      "Centralized property management, with detailed tracking of tenant payments and property documents.",
      "Storage and classification of documents related to owners and tenants by property.",
      "Dynamic Packages for pricing plans with Electronic payment gateway",
      "Add more that admin to the same account, controlling their permissions",
      "Strong Dashboard for owners and landlords (or brokers)",
    ],
  },
  {
    _id: "proj_7",
    type: ["react"],
    name: "Anime Store",
    imgUrl: anime,
    videoUrl: "#",
    live: "#",
    tools: ["React Js", "Context", "Bootstrap", "Css", "Html"],
    desc: "A modern platform designed to enhance the financial efficiency of real estate portfolios for owners and managers.",
    features: [
      "Enables users to manage estates, compounds, contracts, revenues, expenses and more.",
      "Financial management of portfolios, tenant management, rent collection, and maintenance tracking.",
      "Performance indicators for portfolios, such as occupancy rates and financial comparisons.",
      "Notifications, including SMS & Mail alerts, to streamline tenant communication and improve rental efficiency.",
      "Centralized property management, with detailed tracking of tenant payments and property documents.",
      "Storage and classification of documents related to owners and tenants by property.",
      "Dynamic Packages for pricing plans with Electronic payment gateway",
      "Add more that admin to the same account, controlling their permissions",
      "Strong Dashboard for owners and landlords (or brokers)",
    ],
  },
  {
    _id: "proj_8",
    type: ["react"],
    name: "MyKd Games",
    imgUrl: games,
    videoUrl: "#",
    live: "#",
    tools: ["React Js", "Framer motion", "React Bootstrap", "Css", "Html"],
    desc: "A modern platform designed to enhance the financial efficiency of real estate portfolios for owners and managers.",
    features: [
      "Enables users to manage estates, compounds, contracts, revenues, expenses and more.",
      "Financial management of portfolios, tenant management, rent collection, and maintenance tracking.",
      "Performance indicators for portfolios, such as occupancy rates and financial comparisons.",
      "Notifications, including SMS & Mail alerts, to streamline tenant communication and improve rental efficiency.",
      "Centralized property management, with detailed tracking of tenant payments and property documents.",
      "Storage and classification of documents related to owners and tenants by property.",
      "Dynamic Packages for pricing plans with Electronic payment gateway",
      "Add more that admin to the same account, controlling their permissions",
      "Strong Dashboard for owners and landlords (or brokers)",
    ],
  },
  {
    _id: "proj_9",
    type: ["react"],
    name: "Portfolio",
    imgUrl: portfolio,
    videoUrl: "#",
    live: "#",
    tools: ["React Js", "DaisyUi", "Tailwind", "Css", "Html"],
    desc: "A modern platform designed to enhance the financial efficiency of real estate portfolios for owners and managers.",
    features: [
      "Enables users to manage estates, compounds, contracts, revenues, expenses and more.",
      "Financial management of portfolios, tenant management, rent collection, and maintenance tracking.",
      "Performance indicators for portfolios, such as occupancy rates and financial comparisons.",
      "Notifications, including SMS & Mail alerts, to streamline tenant communication and improve rental efficiency.",
      "Centralized property management, with detailed tracking of tenant payments and property documents.",
      "Storage and classification of documents related to owners and tenants by property.",
      "Dynamic Packages for pricing plans with Electronic payment gateway",
      "Add more that admin to the same account, controlling their permissions",
      "Strong Dashboard for owners and landlords (or brokers)",
    ],
  },
  {
    _id: "proj_10",
    type: ["js"],
    name: "Encrypt & Decrypt Images",
    imgUrl: security,
    videoUrl: "#",
    live: "#",
    tools: ["Js", "CryptoJS", "Bootstrap", "Css", "Html"],
    desc: "A modern platform designed to enhance the financial efficiency of real estate portfolios for owners and managers.",
    features: [
      "Enables users to manage estates, compounds, contracts, revenues, expenses and more.",
      "Financial management of portfolios, tenant management, rent collection, and maintenance tracking.",
      "Performance indicators for portfolios, such as occupancy rates and financial comparisons.",
      "Notifications, including SMS & Mail alerts, to streamline tenant communication and improve rental efficiency.",
      "Centralized property management, with detailed tracking of tenant payments and property documents.",
      "Storage and classification of documents related to owners and tenants by property.",
      "Dynamic Packages for pricing plans with Electronic payment gateway",
      "Add more that admin to the same account, controlling their permissions",
      "Strong Dashboard for owners and landlords (or brokers)",
    ],
  },
  {
    _id: "proj_10",
    type: ["js"],
    name: "Mathematics-Queuing-Theory",
    imgUrl: queuingTheory,
    videoUrl: "#",
    live: "#",
    tools: ["Js", "CryptoJS", "Bootstrap", "Css", "Html"],
    desc: "A modern platform designed to enhance the financial efficiency of real estate portfolios for owners and managers.",
    features: [
      "Enables users to manage estates, compounds, contracts, revenues, expenses and more.",
      "Financial management of portfolios, tenant management, rent collection, and maintenance tracking.",
      "Performance indicators for portfolios, such as occupancy rates and financial comparisons.",
      "Notifications, including SMS & Mail alerts, to streamline tenant communication and improve rental efficiency.",
      "Centralized property management, with detailed tracking of tenant payments and property documents.",
      "Storage and classification of documents related to owners and tenants by property.",
      "Dynamic Packages for pricing plans with Electronic payment gateway",
      "Add more that admin to the same account, controlling their permissions",
      "Strong Dashboard for owners and landlords (or brokers)",
    ],
  },
  {
    _id: "proj_11",
    type: ["js"],
    name: "Aqua",
    imgUrl: aqua,
    videoUrl: "#",
    live: "#",
    tools: ["JQuery", "JS", "Bootstrap", "Css", "Html"],
    desc: "A modern platform designed to enhance the financial efficiency of real estate portfolios for owners and managers.",
    features: [
      "Enables users to manage estates, compounds, contracts, revenues, expenses and more.",
      "Financial management of portfolios, tenant management, rent collection, and maintenance tracking.",
      "Performance indicators for portfolios, such as occupancy rates and financial comparisons.",
      "Notifications, including SMS & Mail alerts, to streamline tenant communication and improve rental efficiency.",
      "Centralized property management, with detailed tracking of tenant payments and property documents.",
      "Storage and classification of documents related to owners and tenants by property.",
      "Dynamic Packages for pricing plans with Electronic payment gateway",
      "Add more that admin to the same account, controlling their permissions",
      "Strong Dashboard for owners and landlords (or brokers)",
    ],
  },
  {
    _id: "proj_12",
    type: ["js"],
    name: "Beso Restaurant",
    imgUrl: restaurant,
    videoUrl: "#",
    live: "#",
    tools: ["JS", "Bootstrap", "Css", "Html", "External api(meals)"],
    desc: "A modern platform designed to enhance the financial efficiency of real estate portfolios for owners and managers.",
    features: [
      "Enables users to manage estates, compounds, contracts, revenues, expenses and more.",
      "Financial management of portfolios, tenant management, rent collection, and maintenance tracking.",
      "Performance indicators for portfolios, such as occupancy rates and financial comparisons.",
      "Notifications, including SMS & Mail alerts, to streamline tenant communication and improve rental efficiency.",
      "Centralized property management, with detailed tracking of tenant payments and property documents.",
      "Storage and classification of documents related to owners and tenants by property.",
      "Dynamic Packages for pricing plans with Electronic payment gateway",
      "Add more that admin to the same account, controlling their permissions",
      "Strong Dashboard for owners and landlords (or brokers)",
    ],
  },
  {
    _id: "proj_13",
    type: ["freelance", "js"],
    name: "VG (detect Ransomware)",
    imgUrl: VG,
    videoUrl: "#",
    live: "#",
    tools: ["JS", "Bootstrap", "Css", "Html"],
    desc: "A modern platform designed to enhance the financial efficiency of real estate portfolios for owners and managers.",
    features: [
      "Enables users to manage estates, compounds, contracts, revenues, expenses and more.",
      "Financial management of portfolios, tenant management, rent collection, and maintenance tracking.",
      "Performance indicators for portfolios, such as occupancy rates and financial comparisons.",
      "Notifications, including SMS & Mail alerts, to streamline tenant communication and improve rental efficiency.",
      "Centralized property management, with detailed tracking of tenant payments and property documents.",
      "Storage and classification of documents related to owners and tenants by property.",
      "Dynamic Packages for pricing plans with Electronic payment gateway",
      "Add more that admin to the same account, controlling their permissions",
      "Strong Dashboard for owners and landlords (or brokers)",
    ],
  },
  {
    _id: "proj_14",
    type: ["freelance", "js"],
    name: "Ministries-Complains",
    imgUrl: ministries,
    videoUrl: "#",
    live: "#",
    tools: ["JS", "Pure Css", "Html"],
    desc: "A modern platform designed to enhance the financial efficiency of real estate portfolios for owners and managers.",
    features: [
      "Enables users to manage estates, compounds, contracts, revenues, expenses and more.",
      "Financial management of portfolios, tenant management, rent collection, and maintenance tracking.",
      "Performance indicators for portfolios, such as occupancy rates and financial comparisons.",
      "Notifications, including SMS & Mail alerts, to streamline tenant communication and improve rental efficiency.",
      "Centralized property management, with detailed tracking of tenant payments and property documents.",
      "Storage and classification of documents related to owners and tenants by property.",
      "Dynamic Packages for pricing plans with Electronic payment gateway",
      "Add more that admin to the same account, controlling their permissions",
      "Strong Dashboard for owners and landlords (or brokers)",
    ],
  },
  {
    _id: "proj_15",
    type: ["freelance", "js"],
    name: "Courses_Following",
    imgUrl: t3lm,
    videoUrl: "#",
    live: "#",
    tools: ["JQuery", "JS", "Bootstrap", "Css", "Html"],
    desc: "A modern platform designed to enhance the financial efficiency of real estate portfolios for owners and managers.",
    features: [
      "Enables users to manage estates, compounds, contracts, revenues, expenses and more.",
      "Financial management of portfolios, tenant management, rent collection, and maintenance tracking.",
      "Performance indicators for portfolios, such as occupancy rates and financial comparisons.",
      "Notifications, including SMS & Mail alerts, to streamline tenant communication and improve rental efficiency.",
      "Centralized property management, with detailed tracking of tenant payments and property documents.",
      "Storage and classification of documents related to owners and tenants by property.",
      "Dynamic Packages for pricing plans with Electronic payment gateway",
      "Add more that admin to the same account, controlling their permissions",
      "Strong Dashboard for owners and landlords (or brokers)",
    ],
  },
  {
    _id: "proj_16",
    type: ["js"],
    name: "Contacts (Crud)",
    imgUrl: contacts,
    videoUrl: "#",
    live: "#",
    tools: ["JS", "Bootstrap", "Css", "Html"],
    desc: "A modern platform designed to enhance the financial efficiency of real estate portfolios for owners and managers.",
    features: [
      "Enables users to manage estates, compounds, contracts, revenues, expenses and more.",
      "Financial management of portfolios, tenant management, rent collection, and maintenance tracking.",
      "Performance indicators for portfolios, such as occupancy rates and financial comparisons.",
      "Notifications, including SMS & Mail alerts, to streamline tenant communication and improve rental efficiency.",
      "Centralized property management, with detailed tracking of tenant payments and property documents.",
      "Storage and classification of documents related to owners and tenants by property.",
      "Dynamic Packages for pricing plans with Electronic payment gateway",
      "Add more that admin to the same account, controlling their permissions",
      "Strong Dashboard for owners and landlords (or brokers)",
    ],
  },
  {
    _id: "proj_17",
    type: ["freelance", "js"],
    name: "Saudi-National-Day",
    imgUrl: saudi,
    videoUrl: "#",
    live: "#",
    tools: ["JQuery", "JS", "Bootstrap", "Css", "Html"],
    desc: "A modern platform designed to enhance the financial efficiency of real estate portfolios for owners and managers.",
    features: [
      "Enables users to manage estates, compounds, contracts, revenues, expenses and more.",
      "Financial management of portfolios, tenant management, rent collection, and maintenance tracking.",
      "Performance indicators for portfolios, such as occupancy rates and financial comparisons.",
      "Notifications, including SMS & Mail alerts, to streamline tenant communication and improve rental efficiency.",
      "Centralized property management, with detailed tracking of tenant payments and property documents.",
      "Storage and classification of documents related to owners and tenants by property.",
      "Dynamic Packages for pricing plans with Electronic payment gateway",
      "Add more that admin to the same account, controlling their permissions",
      "Strong Dashboard for owners and landlords (or brokers)",
    ],
  },
  {
    _id: "proj_18",
    type: ["bootstrap"],
    name: "Beso R Us (Toys Store)",
    imgUrl: besorus,
    videoUrl: "#",
    live: "#",
    tools: ["Bootstrap", "Css", "Html"],
    desc: "A modern platform designed to enhance the financial efficiency of real estate portfolios for owners and managers.",
    features: [
      "Enables users to manage estates, compounds, contracts, revenues, expenses and more.",
      "Financial management of portfolios, tenant management, rent collection, and maintenance tracking.",
      "Performance indicators for portfolios, such as occupancy rates and financial comparisons.",
      "Notifications, including SMS & Mail alerts, to streamline tenant communication and improve rental efficiency.",
      "Centralized property management, with detailed tracking of tenant payments and property documents.",
      "Storage and classification of documents related to owners and tenants by property.",
      "Dynamic Packages for pricing plans with Electronic payment gateway",
      "Add more that admin to the same account, controlling their permissions",
      "Strong Dashboard for owners and landlords (or brokers)",
    ],
  },
  {
    _id: "proj_19",
    type: ["bootstrap"],
    name: "Telecome Egypt (We)",
    imgUrl: we,
    videoUrl: "#",
    live: "#",
    tools: ["Bootstrap", "Css", "Html"],
    desc: "A modern platform designed to enhance the financial efficiency of real estate portfolios for owners and managers.",
    features: [
      "Enables users to manage estates, compounds, contracts, revenues, expenses and more.",
      "Financial management of portfolios, tenant management, rent collection, and maintenance tracking.",
      "Performance indicators for portfolios, such as occupancy rates and financial comparisons.",
      "Notifications, including SMS & Mail alerts, to streamline tenant communication and improve rental efficiency.",
      "Centralized property management, with detailed tracking of tenant payments and property documents.",
      "Storage and classification of documents related to owners and tenants by property.",
      "Dynamic Packages for pricing plans with Electronic payment gateway",
      "Add more that admin to the same account, controlling their permissions",
      "Strong Dashboard for owners and landlords (or brokers)",
    ],
  },
  {
    _id: "proj_18",
    type: ["bootstrap"],
    name: "Car Shop",
    imgUrl: car,
    videoUrl: "#",
    live: "#",
    tools: ["Bootstrap", "Css", "Html"],
    desc: "A modern platform designed to enhance the financial efficiency of real estate portfolios for owners and managers.",
    features: [
      "Enables users to manage estates, compounds, contracts, revenues, expenses and more.",
      "Financial management of portfolios, tenant management, rent collection, and maintenance tracking.",
      "Performance indicators for portfolios, such as occupancy rates and financial comparisons.",
      "Notifications, including SMS & Mail alerts, to streamline tenant communication and improve rental efficiency.",
      "Centralized property management, with detailed tracking of tenant payments and property documents.",
      "Storage and classification of documents related to owners and tenants by property.",
      "Dynamic Packages for pricing plans with Electronic payment gateway",
      "Add more that admin to the same account, controlling their permissions",
      "Strong Dashboard for owners and landlords (or brokers)",
    ],
  },
  {
    _id: "proj_18",
    type: ["bootstrap"],
    name: "KFC",
    imgUrl: KFC,
    videoUrl: "#",
    live: "#",
    tools: ["Bootstrap", "Css", "Html"],
    desc: "A modern platform designed to enhance the financial efficiency of real estate portfolios for owners and managers.",
    features: [
      "Enables users to manage estates, compounds, contracts, revenues, expenses and more.",
      "Financial management of portfolios, tenant management, rent collection, and maintenance tracking.",
      "Performance indicators for portfolios, such as occupancy rates and financial comparisons.",
      "Notifications, including SMS & Mail alerts, to streamline tenant communication and improve rental efficiency.",
      "Centralized property management, with detailed tracking of tenant payments and property documents.",
      "Storage and classification of documents related to owners and tenants by property.",
      "Dynamic Packages for pricing plans with Electronic payment gateway",
      "Add more that admin to the same account, controlling their permissions",
      "Strong Dashboard for owners and landlords (or brokers)",
    ],
  },
];
