import {
  diiwan,
  giveagift,
  easyjob,
  zixes,
  ricky,
  notes,
  games,
  anime,
  security,
  queuingTheory,
  VG,
  restaurant,
  ministries,
  besorus,
  aqua,
  t3lm,
  contacts,
  car,
  KFC,
  we,
  saudi,
  portfolio,
} from "../shared/images";

export const projects = [
  {
    _id: "proj_1",
    type: ["freelance", "fullstack","featured"],
    name: "Diwan Amlak",
    imgUrl: diiwan,
    videoUrl: "#",
    github: "https://github.com/BassamHafez/Diwan",
    live: "https://diiwan.com",
    tools: [
      "React Js",
      "Redux Toolkit",
      "React Bootstrap",
      "Css",
      "Html",
      "Node Js",
      "Mongo db",
    ],
    desc: "A modern platform designed to enhance the financial efficiency of real estate portfolios for owners and managers.",
    features: [
      "Manage estates, compounds, contracts, revenues, expenses, and more.",
      "Handle tenant profiles, rent collection, and maintenance requests.",
      "Track portfolio performance with occupancy and financial indicators.",
      "Send SMS and email alerts for efficient tenant communication.",
      "Centralized management of tenant payments and property documents.",
      "Store and categorize documents for both owners and tenants.",
      "Flexible pricing plans with integrated electronic payments.",
      "Multi-admin support with role-based permission control.",
      "Powerful dashboard for owners, landlords, and brokers.",
    ],
  },
  {
    _id: "proj_2",
    type: ["freelance", "fullstack","featured"],
    name: "Give A Gift",
    imgUrl: giveagift,
    github: "https://github.com/BassamHafez/Give-A-Gift",
    videoUrl: "#",
    live: "https://www.giveagift.com.sa/",
    tools: [
      "React Js",
      "Konva.Js",
      "Redux Toolkit",
      "React Bootstrap",
      "Css",
      "Html",
      "Node Js",
      "Mongo db",
    ],
    desc: "A modern gifting platform that allows users to choose or customize gift cards and send them to others, with flexible payment and reward options. Built in collaboration with a backend developer.",
    features: [
      "Choose ready-made gift cards from partner stores.",
      "Customize cards with shapes, colors, messages, and prices.",
      "Cart system with PDF/Excel invoice printing.",
      "Support for user profiles, stores, merchants, and dashboards.",
      "Redeemable gift cards via QR codes (in-store) or promo codes (online).",
      "Earn discounts and cashback on transactions.",
      "Merchant dashboards to track their gift cards.",
      "SMS and email notifications for important updates.",
      "Secure payments via MyFatoorah (Mada, Apple Pay, Mastercard, etc).",
      "Loyalty wallet system to save or transfer reward points.",
    ],
  },
  {
    _id: "proj_3",
    type: ["fullstack","featured"],
    name: "EasyJob - Job Finder Platform",
    imgUrl: easyjob,
    github: "https://github.com/BassamHafez/EasyJob",
    videoUrl: "#",
    live: "#", //live demo here 
    tools: [
      "React Js",
      "Redux Toolkit",
      "Leaflet",
      "React Bootstrap",
      "Css",
      "Html",
      "Node Js",
      "mySQL",
    ],
    desc: "A platform that connects job seekers, employers, and freelancers, simplifying the job search and hiring process with intuitive interfaces and useful features.",
    features: [
      "Job Seeker Portal to search and apply for jobs with advanced filters.",
      "Employer Portal to post and manage job listings, and connect with candidates.",
      "Freelancer Marketplace to showcase skills and explore available projects.",
      "User-friendly interface designed for a seamless experience.",
      "Flexible profiles for both employers and job seekers.",
      "Integrated map to find jobs near your location.",
      "Notifications via WhatsApp and Gmail for new job opportunities.",
    ],
  },
  {
    _id: "proj_4",
    type: ["react","featured"],
    name: "Zixes Movies (First React {Project})",
    imgUrl: zixes,
    github: "https://github.com/BassamHafez/Zixes-Movies",
    videoUrl: "#",
    live: "https://bassamhafez.github.io/Zixes-Movies/#/home",
    tools: [
      "React Js",
      "Context",
      "Bootstrap",
      "Css",
      "Html",
      "External Api (Movies)",
      "Route Api (Auth)",
    ],
    desc: "Zixes is a responsive and dynamic movie web app built with React.js. It fetches real-time data from a movie API to deliver an immersive browsing experience with detailed info, ratings, and reviews.",
    features: [
      "Responsive design for seamless experience across devices.",
      "Dynamic content powered by a real movie API.",
      "Explore a vast collection of movies by category or search.",
      "Detailed movie pages with overviews, ratings, release info, and reviews.",
      "Interactive UI with smooth navigation and transitions.",
      "User-friendly interface with clean layout and intuitive structure.",
      "Modern look and feel using React plugins and components.",
    ],
  },
  {
    _id: "proj_5",
    type: ["react"],
    name: "Ricky Pet Shop (For Kids)",
    imgUrl: ricky,
    github: "https://github.com/BassamHafez/Ricky-pet-shop",
    videoUrl: "#",
    live: "#", //live demo here
    tools: [
      "React Js",
      "Redux Toolkit",
      "React Bootstrap",
      "Css",
      "Html",
      "External Api (Pets)",
      "Route Api (Auth)",
    ],
    desc: "An engaging and responsive e-commerce frontend built with React.js, focused on pets like cats, dogs, and birds. It integrates with an external API to provide real-time pet data and offers a smooth shopping experience.",
    features: [
      "Browse a wide selection of pets (cats, dogs, birds) with detailed info from an external API.",
      "Responsive design optimized for all screen sizes.",
      "Wishlist functionality to mark favorite pets.",
      "Cart system with item management.",
      "Login and registration UI.",
      "Smooth navigation and clean user interface.",
    ],
  },
  {
    _id: "proj_6",
    type: ["fullstack"],
    name: "Notes App",
    imgUrl: notes,
    github: "https://github.com/BassamHafez/Note_App",
    videoUrl: "#",
    live: "#",
    tools: ["React Js", "React Bootstrap", "Css", "Html", "Node Js", "mySQL"],
    desc: "An engaging and responsive e-commerce frontend built with React.js, focused on pets like cats, dogs, and birds. It integrates with an external API to provide real-time pet data and offers a smooth shopping experience.",
    features: [
      "Browse a wide selection of pets (cats, dogs, birds) with detailed info from an external API.",
      "Responsive design optimized for all screen sizes.",
      "Wishlist functionality to mark favorite pets.",
      "Cart system with item management.",
      "Login and registration UI.",
      "Smooth navigation and clean user interface.",
    ],
  },
  {
    _id: "proj_7",
    type: ["react"],
    name: "Anime Store",
    imgUrl: anime,
    github: "https://github.com/BassamHafez/Anime_Store",
    videoUrl: "#",
    live: "#",
    tools: ["React Js", "Context", "Bootstrap", "Css", "Html"],
    desc: "A modern platform designed to enhance the financial efficiency of real estate portfolios for owners and managers.",
    features: [
      "Enables users to manage estates, compounds, contracts, revenues, expenses and more.",
      "Financial management of portfolios, tenant management, rent collection, and maintenance tracking.",
      "Performance indicators for portfolios, such as occupancy rates and financial comparisons.",
      "Notifications, including SMS & Mail alerts, to streamline tenant communication and improve rental efficiency.",
      "Centralized property management, with detailed tracking of tenant payments and property documents.",
      "Storage and classification of documents related to owners and tenants by property.",
      "Dynamic Packages for pricing plans with Electronic payment gateway",
      "Add more that admin to the same account, controlling their permissions",
      "Strong Dashboard for owners and landlords (or brokers)",
    ],
  },
  {
    _id: "proj_8",
    type: ["react"],
    name: "MyKd Games",
    github: "https://github.com/BassamHafez/Games",
    imgUrl: games,
    videoUrl: "#",
    live: "#",
    tools: ["React Js", "Framer motion", "React Bootstrap", "Css", "Html"],
    desc: "A modern platform designed to enhance the financial efficiency of real estate portfolios for owners and managers.",
    features: [
      "Enables users to manage estates, compounds, contracts, revenues, expenses and more.",
      "Financial management of portfolios, tenant management, rent collection, and maintenance tracking.",
      "Performance indicators for portfolios, such as occupancy rates and financial comparisons.",
      "Notifications, including SMS & Mail alerts, to streamline tenant communication and improve rental efficiency.",
      "Centralized property management, with detailed tracking of tenant payments and property documents.",
      "Storage and classification of documents related to owners and tenants by property.",
      "Dynamic Packages for pricing plans with Electronic payment gateway",
      "Add more that admin to the same account, controlling their permissions",
      "Strong Dashboard for owners and landlords (or brokers)",
    ],
  },
  {
    _id: "proj_9",
    type: ["react"],
    name: "Portfolio",
    imgUrl: portfolio,
    github: "https://github.com/BassamHafez/Portfolio",
    videoUrl: "#",
    live: "#",
    tools: ["React Js", "DaisyUi", "Tailwind", "Css", "Html"],
    desc: "A modern platform designed to enhance the financial efficiency of real estate portfolios for owners and managers.",
    features: [
      "Enables users to manage estates, compounds, contracts, revenues, expenses and more.",
      "Financial management of portfolios, tenant management, rent collection, and maintenance tracking.",
      "Performance indicators for portfolios, such as occupancy rates and financial comparisons.",
      "Notifications, including SMS & Mail alerts, to streamline tenant communication and improve rental efficiency.",
      "Centralized property management, with detailed tracking of tenant payments and property documents.",
      "Storage and classification of documents related to owners and tenants by property.",
      "Dynamic Packages for pricing plans with Electronic payment gateway",
      "Add more that admin to the same account, controlling their permissions",
      "Strong Dashboard for owners and landlords (or brokers)",
    ],
  },
  {
    _id: "proj_10",
    type: ["js"],
    name: "Encrypt & Decrypt Images",
    imgUrl: security,
    github: "https://github.com/BassamHafez/Encrypt-Decrypt-Images",
    videoUrl: "#",
    live: "#",
    tools: ["Js", "CryptoJS", "Bootstrap", "Css", "Html"],
    desc: "A modern platform designed to enhance the financial efficiency of real estate portfolios for owners and managers.",
    features: [
      "Enables users to manage estates, compounds, contracts, revenues, expenses and more.",
      "Financial management of portfolios, tenant management, rent collection, and maintenance tracking.",
      "Performance indicators for portfolios, such as occupancy rates and financial comparisons.",
      "Notifications, including SMS & Mail alerts, to streamline tenant communication and improve rental efficiency.",
      "Centralized property management, with detailed tracking of tenant payments and property documents.",
      "Storage and classification of documents related to owners and tenants by property.",
      "Dynamic Packages for pricing plans with Electronic payment gateway",
      "Add more that admin to the same account, controlling their permissions",
      "Strong Dashboard for owners and landlords (or brokers)",
    ],
  },
  {
    _id: "proj_10",
    type: ["js"],
    name: "Mathematics-Queuing-Theory",
    imgUrl: queuingTheory,
    github: "https://github.com/BassamHafez/Mathematics-Queuing-Theory",
    videoUrl: "#",
    live: "#",
    tools: ["Js", "CryptoJS", "Bootstrap", "Css", "Html"],
    desc: "A modern platform designed to enhance the financial efficiency of real estate portfolios for owners and managers.",
    features: [
      "Enables users to manage estates, compounds, contracts, revenues, expenses and more.",
      "Financial management of portfolios, tenant management, rent collection, and maintenance tracking.",
      "Performance indicators for portfolios, such as occupancy rates and financial comparisons.",
      "Notifications, including SMS & Mail alerts, to streamline tenant communication and improve rental efficiency.",
      "Centralized property management, with detailed tracking of tenant payments and property documents.",
      "Storage and classification of documents related to owners and tenants by property.",
      "Dynamic Packages for pricing plans with Electronic payment gateway",
      "Add more that admin to the same account, controlling their permissions",
      "Strong Dashboard for owners and landlords (or brokers)",
    ],
  },
  {
    _id: "proj_11",
    type: ["js"],
    name: "Aqua",
    imgUrl: aqua,
    github: "https://github.com/BassamHafez/Aqua",
    videoUrl: "#",
    live: "#",
    tools: ["JQuery", "JS", "Bootstrap", "Css", "Html"],
    desc: "A modern platform designed to enhance the financial efficiency of real estate portfolios for owners and managers.",
    features: [
      "Enables users to manage estates, compounds, contracts, revenues, expenses and more.",
      "Financial management of portfolios, tenant management, rent collection, and maintenance tracking.",
      "Performance indicators for portfolios, such as occupancy rates and financial comparisons.",
      "Notifications, including SMS & Mail alerts, to streamline tenant communication and improve rental efficiency.",
      "Centralized property management, with detailed tracking of tenant payments and property documents.",
      "Storage and classification of documents related to owners and tenants by property.",
      "Dynamic Packages for pricing plans with Electronic payment gateway",
      "Add more that admin to the same account, controlling their permissions",
      "Strong Dashboard for owners and landlords (or brokers)",
    ],
  },
  {
    _id: "proj_12",
    type: ["js"],
    name: "Beso Restaurant",
    imgUrl: restaurant,
    github: "https://github.com/BassamHafez/Beso-Restaurant",
    videoUrl: "#",
    live: "#",
    tools: ["JS", "Bootstrap", "Css", "Html", "External api(meals)"],
    desc: "A modern platform designed to enhance the financial efficiency of real estate portfolios for owners and managers.",
    features: [
      "Enables users to manage estates, compounds, contracts, revenues, expenses and more.",
      "Financial management of portfolios, tenant management, rent collection, and maintenance tracking.",
      "Performance indicators for portfolios, such as occupancy rates and financial comparisons.",
      "Notifications, including SMS & Mail alerts, to streamline tenant communication and improve rental efficiency.",
      "Centralized property management, with detailed tracking of tenant payments and property documents.",
      "Storage and classification of documents related to owners and tenants by property.",
      "Dynamic Packages for pricing plans with Electronic payment gateway",
      "Add more that admin to the same account, controlling their permissions",
      "Strong Dashboard for owners and landlords (or brokers)",
    ],
  },
  {
    _id: "proj_13",
    type: ["freelance", "js"],
    name: "VG (detect Ransomware)",
    imgUrl: VG,
    github: "https://github.com/BassamHafez/VG",
    videoUrl: "#",
    live: "#",
    tools: ["JS", "Bootstrap", "Css", "Html"],
    desc: "A modern platform designed to enhance the financial efficiency of real estate portfolios for owners and managers.",
    features: [
      "Enables users to manage estates, compounds, contracts, revenues, expenses and more.",
      "Financial management of portfolios, tenant management, rent collection, and maintenance tracking.",
      "Performance indicators for portfolios, such as occupancy rates and financial comparisons.",
      "Notifications, including SMS & Mail alerts, to streamline tenant communication and improve rental efficiency.",
      "Centralized property management, with detailed tracking of tenant payments and property documents.",
      "Storage and classification of documents related to owners and tenants by property.",
      "Dynamic Packages for pricing plans with Electronic payment gateway",
      "Add more that admin to the same account, controlling their permissions",
      "Strong Dashboard for owners and landlords (or brokers)",
    ],
  },
  {
    _id: "proj_14",
    type: ["freelance", "js"],
    name: "Ministries-Complains",
    imgUrl: ministries,
    github: "https://github.com/BassamHafez/Ministries-Complains",
    videoUrl: "#",
    live: "#",
    tools: ["JS", "Pure Css", "Html"],
    desc: "A modern platform designed to enhance the financial efficiency of real estate portfolios for owners and managers.",
    features: [
      "Enables users to manage estates, compounds, contracts, revenues, expenses and more.",
      "Financial management of portfolios, tenant management, rent collection, and maintenance tracking.",
      "Performance indicators for portfolios, such as occupancy rates and financial comparisons.",
      "Notifications, including SMS & Mail alerts, to streamline tenant communication and improve rental efficiency.",
      "Centralized property management, with detailed tracking of tenant payments and property documents.",
      "Storage and classification of documents related to owners and tenants by property.",
      "Dynamic Packages for pricing plans with Electronic payment gateway",
      "Add more that admin to the same account, controlling their permissions",
      "Strong Dashboard for owners and landlords (or brokers)",
    ],
  },
  {
    _id: "proj_15",
    type: ["freelance", "js"],
    name: "Courses_Following",
    imgUrl: t3lm,
    github: "https://github.com/BassamHafez/Courses_Following",
    videoUrl: "#",
    live: "#",
    tools: ["JQuery", "JS", "Bootstrap", "Css", "Html"],
    desc: "A modern platform designed to enhance the financial efficiency of real estate portfolios for owners and managers.",
    features: [
      "Enables users to manage estates, compounds, contracts, revenues, expenses and more.",
      "Financial management of portfolios, tenant management, rent collection, and maintenance tracking.",
      "Performance indicators for portfolios, such as occupancy rates and financial comparisons.",
      "Notifications, including SMS & Mail alerts, to streamline tenant communication and improve rental efficiency.",
      "Centralized property management, with detailed tracking of tenant payments and property documents.",
      "Storage and classification of documents related to owners and tenants by property.",
      "Dynamic Packages for pricing plans with Electronic payment gateway",
      "Add more that admin to the same account, controlling their permissions",
      "Strong Dashboard for owners and landlords (or brokers)",
    ],
  },
  {
    _id: "proj_16",
    type: ["js"],
    name: "Contacts (Crud)",
    imgUrl: contacts,
    github: "https://github.com/BassamHafez/Contacts",
    videoUrl: "#",
    live: "#",
    tools: ["JS", "Bootstrap", "Css", "Html"],
    desc: "A modern platform designed to enhance the financial efficiency of real estate portfolios for owners and managers.",
    features: [
      "Enables users to manage estates, compounds, contracts, revenues, expenses and more.",
      "Financial management of portfolios, tenant management, rent collection, and maintenance tracking.",
      "Performance indicators for portfolios, such as occupancy rates and financial comparisons.",
      "Notifications, including SMS & Mail alerts, to streamline tenant communication and improve rental efficiency.",
      "Centralized property management, with detailed tracking of tenant payments and property documents.",
      "Storage and classification of documents related to owners and tenants by property.",
      "Dynamic Packages for pricing plans with Electronic payment gateway",
      "Add more that admin to the same account, controlling their permissions",
      "Strong Dashboard for owners and landlords (or brokers)",
    ],
  },
  {
    _id: "proj_17",
    type: ["freelance", "js"],
    name: "Saudi-National-Day",
    imgUrl: saudi,
    github: "https://github.com/BassamHafez/Saudi-National-Day",
    videoUrl: "#",
    live: "#",
    tools: ["JQuery", "JS", "Bootstrap", "Css", "Html"],
    desc: "A modern platform designed to enhance the financial efficiency of real estate portfolios for owners and managers.",
    features: [
      "Enables users to manage estates, compounds, contracts, revenues, expenses and more.",
      "Financial management of portfolios, tenant management, rent collection, and maintenance tracking.",
      "Performance indicators for portfolios, such as occupancy rates and financial comparisons.",
      "Notifications, including SMS & Mail alerts, to streamline tenant communication and improve rental efficiency.",
      "Centralized property management, with detailed tracking of tenant payments and property documents.",
      "Storage and classification of documents related to owners and tenants by property.",
      "Dynamic Packages for pricing plans with Electronic payment gateway",
      "Add more that admin to the same account, controlling their permissions",
      "Strong Dashboard for owners and landlords (or brokers)",
    ],
  },
  {
    _id: "proj_18",
    type: ["bootstrap"],
    name: "Beso R Us (Toys Store)",
    imgUrl: besorus,
    github: "https://github.com/BassamHafez/Beso-R-Us",
    videoUrl: "#",
    live: "#",
    tools: ["Bootstrap", "Css", "Html"],
    desc: "A modern platform designed to enhance the financial efficiency of real estate portfolios for owners and managers.",
    features: [
      "Enables users to manage estates, compounds, contracts, revenues, expenses and more.",
      "Financial management of portfolios, tenant management, rent collection, and maintenance tracking.",
      "Performance indicators for portfolios, such as occupancy rates and financial comparisons.",
      "Notifications, including SMS & Mail alerts, to streamline tenant communication and improve rental efficiency.",
      "Centralized property management, with detailed tracking of tenant payments and property documents.",
      "Storage and classification of documents related to owners and tenants by property.",
      "Dynamic Packages for pricing plans with Electronic payment gateway",
      "Add more that admin to the same account, controlling their permissions",
      "Strong Dashboard for owners and landlords (or brokers)",
    ],
  },
  {
    _id: "proj_19",
    type: ["bootstrap"],
    name: "Telecome Egypt (We)",
    imgUrl: we,
    github: "https://github.com/BassamHafez/Telecome-Egypt-WE-",
    videoUrl: "#",
    live: "#",
    tools: ["Bootstrap", "Css", "Html"],
    desc: "A modern platform designed to enhance the financial efficiency of real estate portfolios for owners and managers.",
    features: [
      "Enables users to manage estates, compounds, contracts, revenues, expenses and more.",
      "Financial management of portfolios, tenant management, rent collection, and maintenance tracking.",
      "Performance indicators for portfolios, such as occupancy rates and financial comparisons.",
      "Notifications, including SMS & Mail alerts, to streamline tenant communication and improve rental efficiency.",
      "Centralized property management, with detailed tracking of tenant payments and property documents.",
      "Storage and classification of documents related to owners and tenants by property.",
      "Dynamic Packages for pricing plans with Electronic payment gateway",
      "Add more that admin to the same account, controlling their permissions",
      "Strong Dashboard for owners and landlords (or brokers)",
    ],
  },
  {
    _id: "proj_18",
    type: ["bootstrap"],
    name: "Car Shop",
    imgUrl: car,
    github: "https://github.com/BassamHafez/Car-Shop",
    videoUrl: "#",
    live: "#",
    tools: ["Bootstrap", "Css", "Html"],
    desc: "A modern platform designed to enhance the financial efficiency of real estate portfolios for owners and managers.",
    features: [
      "Enables users to manage estates, compounds, contracts, revenues, expenses and more.",
      "Financial management of portfolios, tenant management, rent collection, and maintenance tracking.",
      "Performance indicators for portfolios, such as occupancy rates and financial comparisons.",
      "Notifications, including SMS & Mail alerts, to streamline tenant communication and improve rental efficiency.",
      "Centralized property management, with detailed tracking of tenant payments and property documents.",
      "Storage and classification of documents related to owners and tenants by property.",
      "Dynamic Packages for pricing plans with Electronic payment gateway",
      "Add more that admin to the same account, controlling their permissions",
      "Strong Dashboard for owners and landlords (or brokers)",
    ],
  },
  {
    _id: "proj_18",
    type: ["bootstrap"],
    name: "KFC",
    imgUrl: KFC,
    github: "https://github.com/BassamHafez/KFC",
    videoUrl: "#",
    live: "#",
    tools: ["Bootstrap", "Css", "Html"],
    desc: "A modern platform designed to enhance the financial efficiency of real estate portfolios for owners and managers.",
    features: [
      "Enables users to manage estates, compounds, contracts, revenues, expenses and more.",
      "Financial management of portfolios, tenant management, rent collection, and maintenance tracking.",
      "Performance indicators for portfolios, such as occupancy rates and financial comparisons.",
      "Notifications, including SMS & Mail alerts, to streamline tenant communication and improve rental efficiency.",
      "Centralized property management, with detailed tracking of tenant payments and property documents.",
      "Storage and classification of documents related to owners and tenants by property.",
      "Dynamic Packages for pricing plans with Electronic payment gateway",
      "Add more that admin to the same account, controlling their permissions",
      "Strong Dashboard for owners and landlords (or brokers)",
    ],
  },
];
